export const MAX_MOLECULE_LENGTH = 5
export const MAX_CHALLENGES = 10
export const ALERT_TIME_MS = 2000
export const REVEAL_TIME_MS = 350
export const GAME_LOST_INFO_DELAY = (MAX_MOLECULE_LENGTH + 1) * REVEAL_TIME_MS
